name: Update SVG Widget

on:
  repository_dispatch:
    types: [new_scrobble]

permissions:
  contents: write 

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests pylast

      - name: Crear archivo .nojekyll
        run: touch .nojekyll

      - name: Ejecutar script
        run: python NotionYTWidget.py

      - name: Commit y push de cambios
        run: |
          git config --global user.name "Gochi Bot"
          git config --global user.email "gochi@example.com"
          git add ipodbase_updated.svg index.html .nojekyll
          git commit -m "🔄 Actualización automática del widget con nuevo scrobble" || echo "Nada que commitear"
          git push
